'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SelectionDropdown from "@/components/SelectionDropdown";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-xl text-center mt-4 ">Algs Visualizer</h1>
        <SelectionDropdown />
        {children}</body>
    </html>
  );
}
